apiVersion: v1
kind: Config
clusters:
- name: "odp-hz"
  cluster:
    server: "https://65.108.12.152:32443/k8s/clusters/c-xjj6t"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMxT1RjNQpPREU1TVRBZUZ3MHlOVEV3TURjd01EUTVOVEZhRncwek5URXdNRFV3TURRNU5URmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56VTVOems0TVRreE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRU52bC9XSUQrOVp1VwpBMlFvbXEvYndEbzVjbXN0V0xmT1FKSkRKV\
      UdBSXhMMkwzWkxoNDdqV1Y0VER1bEEyLzhxajgySzlSelJGSjgyCjlCZm4xNzR1UDZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGR\
      WFJN21xMDUwQWVBcktGRWJSekxlMUIwUkZPTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUhkaQo4Y\
      jZDOWN3UW80MHVpdllJd2F0QzFOSkR1Qy9FNFNyTmp2cmxvdms5QWlBTGdtNk0rRmMvZ2xDaFVkM\
      GFvWVNKCmdNL2w0NU9KeDg3b0ExVXNVTU5jRmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "odp-hz"
  user:
    token: "kubeconfig-user-djjqcxtjgf:52drplm6lfg2lpprjsq5p82xg8g5pnzfzng6rktwg55stftkwmphbn"


contexts:
- name: "odp-hz"
  context:
    user: "odp-hz"
    cluster: "odp-hz"

current-context: "odp-hz"

